# Generated by Django 4.0.5 on 2022-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drcuser',
            name='OTP_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
